[package]
name = "Argyle-Web-Ui"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
wasm-bindgen = "0.2.89"
wasm-pack = "0.12.1"